myecs/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.urls import path, include
from rest_framework import routers

from note.views import LogViewSet, KeyLogViewSet
from note.views import MainView

router = routers.DefaultRouter()
router.register(r'logs', LogViewSet)
router.register(r'keylogs', KeyLogViewSet)

urlpatterns = [
    path('', MainView.as_view(), name='index'),
    path('', include('note.urls')),

    url(r'^admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include(router.urls)),
]
# ログイン画面のタイトルを変更
admin.site.site_header = 'MyECS'

note/urls.py
from django.urls import path
from .views import listfunc, formfunc, mybpmfunc, updataformfunc, deleteformfunc

urlpatterns = [
    path('note/list/', listfunc, name='list'),
    ##path('', listfunc, name='list'),
    path('note/', formfunc, name='form'),
    path('note/<int:note_id>/updata/', updataformfunc, name='updata'),
    path('note/<int:note_id>/delete/', deleteformfunc, name='delete'),
    ##path('detail/<int:pk>', detailfunc, name='detail'),
    path('mybpm/', mybpmfunc, name='mybpm'),
]

note/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

## ノート機能 https://www.tech-tech.xyz/python-django-tutorial2-html.html
class Category(models.Model):
    """ノートのカテゴリ"""
    name = models.CharField('タイトル', max_length=255)
    color = models.TextField('カラー', blank=True, null=True)

    def __str__(self):
        return self.name
    #def get_posts_count(self):
        #return Note.objects.filter(name=self).count()
## 紐付け https://qiita.com/saka___21/items/5233f4bb4a252bcaf44e
class Note(models.Model):
    note_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='ユーザ名')
    title = models.CharField('タイトル', max_length=20)
    content = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ')
    created_at = models.DateTimeField('作成日', auto_now_add=True)#作成時間 自動
    updated_at = models.DateTimeField('更新日', auto_now=True)#更新時間 自動

    def __str__(self):
        return str(self.note_id)

    class Meta:
        verbose_name = 'Note'
        verbose_name_plural = 'Note'

## 打鍵数を記録する
class KeyLog(models.Model):
    note_id = models.ForeignKey(Note, to_field='note_id', on_delete=models.PROTECT, verbose_name='note_id')
    counted_at = models.DateTimeField('カウント時間',auto_now_add=True)
    count = models.IntegerField('文字数')
    key = models.IntegerField('キーコード', blank=True, null=True)

    def __str__(self):
        return str(self.note_id)+','+str(self.count)+','+str(self.counted_at)
    class Meta:
        verbose_name = 'KeyLog'
        verbose_name_plural = 'KeyLog'

## 心拍数をwebAPIで取得する
class HeartLog(models.Model):
    # 登録時間はサーバ側で自動的
    user_id = models.IntegerField(
        verbose_name='ユーザID',
        blank=True
    )
    measured_at = models.DateTimeField(#自動
        verbose_name='登録時間',
        auto_now_add=True,
    )
    bpm = models.FloatField(
        verbose_name='心拍数',
        blank=True
    )

    # 以下は管理サイト上の表示設定
    def __str__(self):
        return self.measured_at

    class Meta:
        verbose_name = '心拍データ'
        verbose_name_plural = '心拍データ'

note/forms.py
from django import forms
from .models import Note

"""ノート用のフォーム"""
class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title', 'category', 'content')

        widgets = {
            'content': forms.Textarea(attrs={'rows':15, 'cols':70}),
        }

note/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

import django_filters
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.views.generic import ListView
from rest_framework import serializers
from rest_framework import viewsets
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated

from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import User

from .models import HeartLog, Note, Category, KeyLog
from .forms import NoteForm

from django.http import JsonResponse
from django.http import QueryDict

#新規    'bootstrap4',           # django-bootstrap4
def formfunc(request):
    if request.method == 'GET':## 新規作成
        form = NoteForm()
    elif request.method == 'POST':## 保存すると「updata/<note_id>」へredirect
        form = NoteForm(request.POST)
        if form.is_valid():##
            note = form.save(commit=False)
            note.user = request.user
            note_id=note.note_id
            note.save()
            return redirect('updata', note_id=note.note_id)
    return render(request, 'form.html', {'form': form})

#編集 & 分析
def updataformfunc(request, note_id):
    note = get_object_or_404(Note, note_id=note_id)# 対象の記事情報を取得
    if request.method == 'POST':# 更新
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            note.save()
            return redirect('updata', note_id=note_id)
    else: # GETの場合はデータを表示
        form = NoteForm(instance=note)
    return render(request, 'updata.html', {'form': form, 'note': note})
# ノート削除
def deleteformfunc(request, note_id):
    note = get_object_or_404(Note, note_id=note_id)
    keylogs = KeyLog.objects.filter(note_id=note_id)
    keylogs.delete()
    note.delete()
    notes = Note.objects.all()
    return redirect('list')#render(request, 'list.html', {'notes': notes})
# ノート一覧
@login_required
def listfunc(request):
    notes = Note.objects.filter(user=request.user)
    categories = notes.order_by('category').distinct().values_list("category", flat=True)
    c = Category.objects.filter()
    ##notes = Note.objects.get(user=request.user)
    return render(request, 'list.html', {'notes': notes, 'categories':categories, 'c': c})

# 心拍グラフの表示
def mybpmfunc(request):
    ##bpms = HeartLog.objects.get(user=get_user_model())
    return render(request, 'mybpm.html')

## bpm入出力
class LogSerializer(serializers.ModelSerializer):
    class Meta:
        model = HeartLog
        fields = '__all__'
## 検索 http://<endpoint>/?<fieldname>__gte=YYYY-MM-DD%20HH:mm:ss
class LogFilter(django_filters.FilterSet):
    class Meta:
        model = HeartLog
        fields = {'measured_at': ['gte', ], }
## WebAPIの定義
class LogViewSet(viewsets.ModelViewSet):
    queryset = HeartLog.objects.all().order_by("measured_at")

    serializer_class = LogSerializer
    filter_class = LogFilter

    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)

## keylog入出力
class KeyLogSerializer(serializers.ModelSerializer):
    class Meta:
        model = KeyLog
        fields = '__all__'
## KeyLog検索 http://<endpoint>/?<note_id>__gte=1~
class KeyLogFilter(django_filters.FilterSet):
    class Meta:
        model = KeyLog
        fields = {'note_id': ['gte', ], }
## KeyLog WebAPIの定義
class KeyLogViewSet(viewsets.ModelViewSet):
    queryset = KeyLog.objects.all().order_by("note_id")
    serializer_class = KeyLogSerializer
    filter_class = KeyLogFilter

class MainView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Note.objects.all()
        context['category_list'] = Category.objects.all()
        context['note_list'] = KeyLog.objects.order_by('note_id').distinct().values_list("note_id", flat=True).reverse()[:5]
        return context

templates/base.html
<!-- 雛形　ページ表示view -->
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>Mynote</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  </head>

  <body style="margin-right: 0px;">
    <!-- 上部nav -->
    <div class="nav1">
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
      <link rel="stylesheet" id="theme_link" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.3.1/flatly/bootstrap.min.css">
      <div class="fixed-left">
        <nav class="navbar navbar-expand-md navbar-dark bg-primary">
          <a class ="navbar-brand" href="{% url 'index' %}">Mynote</a>
          <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="nav nav-sidebar">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="">
                    note
                  </a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'form' %}">New</a>
                    <a class="dropdown-item" href="{% url 'list' %}">Open</a>
                  </div>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'mybpm' %}">bpm</a></li>
            </ul>

            <ul class="navbar-nav ml-auto"><!-- 右寄せ -->
              {% if user.is_authenticated　%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">
                  {{ user.get_username }}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">ログイン</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </nav>
      </div>
    </div>

    <div class="container-fluid">
        <div class="row">

          <div class="clearfix"></div>
          <div class="col-sm-2 col-md-2 sidebar navbar-light">
            <div class="time">
              {% block time %}{% endblock %}
            </div>
            <div class='category'>
              {% block category %}{% endblock %}
            </div>
            <div class='footer'>
            {% block footer %}{% endblock %}
            </div>
          </div>

          <div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 main">
            <div class='note'>
              {% block content %}{% endblock %}
            </div>
            <div class='chart'>
              {% block chart %}{% endblock %}
            </div>
          </div>

          <div class="col-sm-2 col-md-2 sidebar navbar-light">
            <div class="left">
            {% block concent %}{% endblock %}
            </div>
          </div>

        </div>
    </div>
  </body>
</html>

templates/form.html
<!-- 新規ノートの作成-->
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<h1></h1>
<div class="form">
  <form method="POST">
      {% csrf_token %}
      <p>title: {{ form.title }}</p>
      <p>category: {{ form.category }}</p>
      <p>{{ form.content }}</p>
  <button id="submit_btn" type="submit" class="btn btn-dark" value="Submit">保存</button>
  </form>
  <p><span class="show-count">0</span>byte</p>
</div>
<!-- 終了時刻の入力要求・updata.htmlへ値渡す -->
<!-- フォームの文字数カウントを行うjavascriptプログラム #id_note_id -->
<!-- タイトル・カテゴリが入力済ならノートをデータベースに新規保存し、編集画面へ移る -->
<script>
  $(function(){
    $('#id_content').keyup(function(){
      var count = $(this).val().length;
      $('.show-count').text(count);
    });
  });
  $('#id_category').on('change', () => {
    if( $('#id_title').val().length > 0){
      $("#submit_btn").click();
    }
  });
</script>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block category %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<h1 class="my-3"></h1>
<div style="padding: 5px; margin-bottom: 10px; border: 1px dashed #2C3E50; border-radius: 5px;">
    {% for category in category_list %}
    <div class="category">
      <span>{{ category.name }}
      <font color={{category.color}}>●</font>
      </span>
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<h1 class="my-3"></h1>
{% for recent in note_list %}
  {% for note in object_list %}
    {% if note.note_id == recent %}
    <div class="card mb-3">
      <div class="card-body">
        <div class='card-content'>
          <h5 class="card-title">{{ note.title }} ({{ note.user }})</h5>
          <div class="card-text" id="frame">
            <span>{{ note.category }}
            <font color={{note.category.color}}>●</font>
          </span>
          <!--span>更新日: {{ note.updated_at }}</span-->
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  {% endfor %}
{% endfor %}

{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- https://zerofromlight.com/blogs/detail/60/ -->
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<div class='list'>
  <h1 class="my-3"></h1>
  {% for note in notes %}
  {% if note.user.get_username == user.get_username %}
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title">
        <a href="{% url 'updata' note.note_id %}">{{ note.title }}</a>
      </h5>
      <div class="card-text" id="frame">
        <span class="left">{{ note.category }}
        <font color={{note.category.color}}>●</font></span>
      <span class="right">更新日: {{ note.updated_at }}</span>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
{% endblock %}

{% block category %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<h1 class="my-3"></h1>

<div style="padding: 10px; margin-bottom: 10px; border: 1px dashed #2C3E50; border-radius: 5px;">
  <a>{{ notes|length }} notes</a>
  {% for category in categories %}
    {% for c in c %}
    {% if c.id == category %}
    <div class="category">
      <span>{{ c.name }}
        <font color={{c.color}}>●</font>
      </span>
    </div>
    {% endif %}
    {% endfor %}
  {% endfor %}
</div>

{% endblock %}

templates/updata.html
<!-- ノートの編集画面 -->
{% extends 'base.html' %}

{% block footer %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<input type="time" id="time" name="time" step="60"></input>
{% endblock %}

{% block time %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<h1 class="my-3"></h1>
<div class="balloon" id="balloon" style="visibility: hidden;">
  <p><span class="span2">あと0時間10分</span></p>
</div>
{% endblock %}

{% block concent %}
<div id="concent" class='concent'>
  <p> <span class="span1" id="span1"></span></p>
</div>
<div id="moni" class='moni'>
</div>
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" id="theme_link" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.3.1/flatly/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<h1></h1>
<div class="form">
  <form method="POST" action="{% url 'updata' note.note_id %}">
      {% csrf_token %}
      <p>title: {{ form.title }}</p>
      <p>category: {{ form.category}}</p>
      <p>{{ form.content }}</p>
  <button id="submit_btn" type="submit" class="btn btn-dark" value="Submit">保存</button>
  <button id="delete_btn" type="button" class="btn btn-dark" onclick="location.href='{% url 'delete' note.note_id %}'">削除</button>
  <button id="keylog_enter_btn" type="button" class="btn btn-dark" value="keylog_btn" style="visibility: hidden;">http</button>
  <button id="keylog_delete_btn" type="button" class="btn btn-dark" value="keylog_btn" style="visibility: hidden;">http</button>
  </form>
  <p><span class="show-count">0</span>byte</p>
</div>

<!-- フォーム('#id_content')の文字数カウントを行うjavascriptプログラム -->
<!-- エンターキーを押した時にsubmitするプログラム -->
<!-- クッキーを取得するプログラム -->
<!-- 保存ボタンを押したタイミングで、文字数とnote_idをfetchプログラムで/api/keylogs/へhttp送信 -->
<!-- 定期的に"#submit_btn"を押して、保存を行うプログラム -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/locale/ja.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.0/underscore-min.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js" charset="utf-8"></script>
<script>
$(function(){
  $('#id_content').keyup(function(e){//keyupはisComposingがtrue(Chrome Firefox	Safari確認済み)
    var count = $(this).val().length;
    $('.show-count').text(count);

    if( e.which == 13 || e.key== 'Enter'){//enter e.which == 13 ||  backspace 押した際
       $("#keylog_enter_btn").click();
    }
    if( e.which == 8 || e.key== 'BackSpace'){//enter e.which == 13 ||  backspace 押した際
        $('.span2').text();
        $("#keylog_delete_btn").click();
        if(document.getElementById("balloon").style.visibility != "hidden"){
          document.getElementById("balloon").style.visibility = "hidden";
          $('.span2').text("");
        }
    }
  });
});
setInterval('state()', 60000);
setInterval('timeSet()', 300000);
const getCookie = name =>{
      if (document.cookie && document.cookie !== '') {
          for (const cookie of document.cookie.split(';')){
              const [key, value] = cookie.trim().split('=');
              if(key === name) {
                  return decodeURIComponent(value);
              }
          }
      }
  };
function state() {
    let bpm_data = new Array(2).fill(0);
    let bpm_time = new Array(2).fill(0);
    let key_data = new Array(2).fill(0);
    let key_time = new Array(2).fill(0);

    var times = '3';// 前3分間の時間幅を指定
    var param = moment().subtract(times,'minutes').format('YYYY-MM-DD HH:mm:ss')
//心拍数
    $.getJSON('/api/logs?created_at__gte=' + param)
        .done(function (source) { // もしもパラメータ(前一時間の範囲)でデータがあれば
          var user = "{{ user.get_username }}";
          var count = 1;
          //前一定時間(times)の間において、該当ユーザの2件の最新bpmデータ
          if(source.length > 1){
            for(let i=source.length-1; i>0; i--){
              //let bpm_data = new Array(3);
              const json = JSON.parse( JSON.stringify(source[i]) );
              bpm_user = json.user_id;
              if( bpm_user == 0 ){// 該当ユーザであれば[0]~[1]の2件のbpmデータ
                bpm_data[count] = json.bpm;
                bpm_time[count] = json.measured_at;
                count--;
                if( count < 0 )break;
              }
            }
          }
            if( count < 0 ){//bpmが2件あれば
              $.getJSON('/api/keylogs?created_at__gte=' + param)//打鍵数
                  .done(function (key_source) { // もしもパラメータ(前一時間の範囲)でデータがあれば
                    var note_id = "{{ note.note_id }}";
                    var miss = 1;
                    var tmp = 180;

                    var now = new Date();
                    if(key_source.length > 1){//前一定時間(times)の間において、該当ユーザ2件の最新bpmデータ
                      count = 1;
                      for(let i = key_source.length-1; i>=0 ; i--){//前一定時間(times)の間において、該当ユーザの最新のデータから検索かける
                        const json = JSON.parse( JSON.stringify(key_source[i]) );
                        if(json.note_id == note_id){// 該当ノートであれば
                          if(count == 1 ){
                            var diff = now.getTime()-new Date(json.counted_at).getTime();//new Date(bpm_time[count]).getTime()
                            diff = diff/1000; //秒
                            if(diff*diff < tmp*tmp){//最新の値
                              tmp = diff;
                              key_data[count] = json.count;
                              key_time[1] = json.counted_at;
                              if(json.key=='8')miss++;
                            }else count--;
                          }
                          if(count == 0){
                            tmp = 180;
                            var diff = new Date(json.counted_at).getTime() - now.getTime();
                            diff = diff/1000 + 60; //秒
                            if(diff*diff < tmp*tmp){//最新の値
                              tmp = diff;
                              key_data[count] = json.count;
                              key_time[0] = json.counted_at;
                              if(json.key=='8')miss++;
                            }else count--;
                          }
                          if( count<0 ){
                            break;
                          }
                        }
                      }

                    }
////////* 判定 *///////////
                    if(count<0){//打鍵数のデータが2件あれば
                      var bpm_up_rate = bpm_data[1]-bpm_data[0];//心拍の上昇率
                      var time = new Date(key_time[1]).getTime()-new Date(key_time[0]).getTime();
                      time = time/60000;
                      var key_up;
                      if(time==0)key_up=0;
                      else key_up = (key_data[1]-key_data[0])/time; //1minあたりの打鍵数
                      miss = miss/time;
                      console.log("bpm上昇");
                      console.log(bpm_up_rate);
                      if(key_up<0)key_up=0;
                      //sessionStorage.setItem('CT', 50);
                      var CT=0;
                      var CT0;
                      var KEYUP0;
                      var key_up_rate;
                      if(sessionStorage.getItem('NOTE') == null){
                          CT0 = 50;
                      }
                      else if(sessionStorage.getItem('CT')==null || isNaN(sessionStorage.getItem('CT')) ||  parseInt(sessionStorage.getItem('NOTE')) != note_id){
                        CT0 = parseFloat(50);
                      }else CT0 = parseFloat(sessionStorage.getItem('CT'));

                      if(sessionStorage.getItem('KEYUP0')==null || isNaN(sessionStorage.getItem('KEYUP0'))){
                        KEYUP0 = parseFloat(0);
                      }else KEYUP0 = parseFloat(sessionStorage.getItem('KEYUP0'));

                      if(KEYUP0 < 1){
                        key_up_rate = 0;
                      } else {
                        key_up_rate = (key_up-KEYUP0)/KEYUP0;
                        if(key_up_rate<0)key_up_rate *= -1;
                      }//0~10くらい？
                      console.log("CT0");
                      console.log(parseFloat(CT0));
                      CT = parseFloat(CT0) + parseFloat(10*key_up_rate*bpm_up_rate*(miss/(key_up+miss)));
                        //CT = parseFloat(CT0) + parseFloat(500*key_up_rate*bpm_up_rate*(miss/(key_up+miss)));
                      if(CT>=100)CT=100;
                      else if(CT<0)CT=0;
                      sessionStorage.setItem('CT', CT.toFixed(16));
                      sessionStorage.setItem('KEYUP0', key_up.toFixed(16));
                      sessionStorage.setItem('NOTE', note_id);
                      console.log("打鍵速度の差");

                      console.log(key_up);
                      console.log(KEYUP0);

                      console.log("打鍵速度の変化　ミス発生率 ct");
                      console.log(key_up_rate);
                      console.log((miss/(key_up+miss)));
                      console.log(10*key_up_rate*bpm_up_rate*(miss/(key_up+miss)));
                      console.log(CT);

//                      if(CT==CT0){
//                      }else if(CT < 40){
//                        $('.span1').text(CT+": 集中していない");
//                      }else{
//                        $('.span1').text(CT+": 集中している");
//                        if(document.getElementById("time").value != ""){
//                          $('.span2').text("");
//                        }
//                      }
                    }
/////////////////////////
             })
           }
   });
}
function timeSet(){
  var input_time = document.getElementById("time").value;
  const input = input_time.split(':');
  var date = new Date();
  var min=0;
  var h=0;
  min += Number(input[1])-date.getMinutes();
  if(min<0){
    h-=1;
  }
  h += Number(input[0])-date.getHours();
  if(h<0){}
  else{
    $('.span2').text("あと"+String(h)+"時間"+String(min)+"分");
    document.getElementById("balloon").style.visibility ="visible";
    console.log("あと"+String(h)+"時間"+String(min)+"分");
    //sessionStorage.setItem('TIME')=="あと"+String(h)+"時間"+String(min)+"分";
  }
}
$(document).on("click", "#keylog_delete_btn", function(){
   var button = $(this);
   var val_note_id = "{{ note.note_id }}";//$('#id_note_id').val();//undefinedになってた
   var val_count = $('#id_content').val().length;// フォーム内の文字数

   var data = { "count": val_count,  "note_id": val_note_id, "key":8};
   var json_data = "{" +"\"note_id\":"+ val_note_id +"," +"    \"count\": "+ val_count +","+ "    \"key\": "+ 8 +"}";
   var json_text = JSON.stringify(data);

   var xmlHttpRequest = new XMLHttpRequest();
   var url = "https://mynote.pythonanywhere.com/api/keylogs/";
  //var url = "https://mynote.pythonanywhere.com/api/keylogs/"; //IP変え忘れ注意
   var user = "sugairisa";//
   var pass = "science1220";//
   var authorizationBasic = user+ ':' + pass;
   const param  = {
     method: "POST",
     headers: {
       "Accept": "application/json",
       "Content-Type": "application/json",
       "X-Requested-With": "XMLHttpRequest",
       "X-CSRFToken": getCookie("csrftoken"),
     },
     body: JSON.stringify(data)
   };
   sendServer(url, param);
 });
$(document).on("click", "#keylog_enter_btn", function(){
   var button = $(this);
   var val_note_id = "{{ note.note_id }}";//$('#id_note_id').val();//undefinedになってた
   var val_count = $('#id_content').val().length;// フォーム内の文字数

   var data = { "count": val_count,  "note_id": val_note_id, "key":13};
   var json_data = "{" +"\"note_id\":"+ val_note_id +"," +"    \"count\": "+ val_count +","+ "    \"key\": "+ 13 +"}";
   var json_text = JSON.stringify(data);

   var xmlHttpRequest = new XMLHttpRequest();
   var url = "https://mynote.pythonanywhere.com/api/keylogs/";
  //var url = "https://mynote.pythonanywhere.com/api/keylogs/"; //IP変え忘れ注意
   var user = "sugairisa";//
   var pass = "science1220";//
   var authorizationBasic = user+ ':' + pass;
   const param  = {
     method: "POST",
     headers: {
       "Accept": "application/json",
       "Content-Type": "application/json",
       "X-Requested-With": "XMLHttpRequest",
       "X-CSRFToken": getCookie("csrftoken"),
     },
     body: JSON.stringify(data)
   };
   sendServer(url, param);
 });
 function sendServer(url, param){
  fetch(url, param)
    .then((response)=>{
      return response.json();
    })
    .then((data)=>{
        //console.log('Success:', JSON.stringify(data));
    })
    .catch((error)=>{
      console.log(`[error2] ${error}`);
    });
}
</script>
{% endblock %}